const POSTS_REQUESTED = 'POSTS_REQUESTED';
const POSTS_RECEIVED = 'POSTS_RECEIVED';
const POSTS_REJECTED = 'POSTS_REJECTED';

export const MODAL_ACTIONS = { CHANGE_MODAL: 'CHANGE_MODAL' };

const AUTH_REQUESTED = 'AUTH_REQUESTED';
const AUTH_SUCCEED = 'AUTH_SUCCEED';
const AUTH_REJECTED = 'AUTH_REJECTED';
const AUTH_SIGN_OUT = 'AUTH_SIGN_OUT';
const AUTH_VERIFY_REQUESTED = 'AUTH_VERIFY_REQUESTED';
const AUTH_VERIFY_SUCCEED = 'AUTH_VERIFY_SUCCEED';
const AUTH_VERIFY_REJECTED = 'AUTH_VERIFY_REJECTED';

const USER_REQUESTED = 'USER_REQUESTED';
const USER_RECEIVED = 'USER_RECEIVED';
const USER_REJECTED = 'USER_REJECTED';

const EDIT_USER_REQUESTED = 'EDIT_USER_REQUESTED';
const EDIT_USER_RECEIVED = 'EDIT_USER_RECEIVED';
const EDIT_USER_REJECTED = 'EDIT_USER_REJECTED';

export { POSTS_REQUESTED, POSTS_RECEIVED, POSTS_REJECTED };

export {
  AUTH_REQUESTED,
  AUTH_VERIFY_REQUESTED,
  AUTH_SUCCEED,
  AUTH_VERIFY_SUCCEED,
  AUTH_REJECTED,
  AUTH_VERIFY_REJECTED,
  AUTH_SIGN_OUT
};

export { USER_REQUESTED, USER_RECEIVED, USER_REJECTED };

export { EDIT_USER_REQUESTED, EDIT_USER_RECEIVED, EDIT_USER_REJECTED };
